
version: 0.2

phases:
  install:
    runtime-versions:
      java:   openjdk8
    commands:
      - echo install 

  pre_build:
    commands:
      - command
      - echo pre_build
  build:
    commands:
      - mvn package
      - echo build
 
  post_build:
  
    commands:
      - echo post build
    

artifacts:
  files:
    - location
    - location
 